import { randomBytes } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import type { RowDataPacket } from "mysql2";
import { SESSION_COOKIE, readSession } from "@/lib/auth";
import { getDb } from "@/lib/db";
export const runtime = "nodejs";
async function current(request: NextRequest) { const token = request.cookies.get(SESSION_COOKIE)?.value; return token ? readSession(token) : null; }
export async function GET(request: NextRequest) { const session = await current(request); if (!session) return NextResponse.json({ message: "请先登录" }, { status: 401 }); const [rows] = await getDb().execute<RowDataPacket[]>("SELECT id, title, content, announcement_type AS type, author_id AS authorId, is_pinned AS pinned, view_count AS views, DATE_FORMAT(created_at, '%Y-%m-%d %H:%i:%s') AS createdAt FROM announcements ORDER BY is_pinned DESC, created_at DESC"); return NextResponse.json({ announcements: rows.map((row) => ({ ...row, pinned: Boolean(row.pinned), views: Number(row.views) })) }); }
export async function POST(request: NextRequest) { const session = await current(request); if (!session || !["admin", "superadmin", "manager"].includes(session.role)) return NextResponse.json({ message: "仅管理员可以发布公告。" }, { status: 403 }); const input = await request.json() as { title?: string; content?: string; type?: string; pinned?: boolean }; const title = String(input.title || "").trim().slice(0, 255); const content = String(input.content || "").trim(); const type = ["notice", "policy", "event", "urgent"].includes(String(input.type)) ? String(input.type) : "notice"; if (!title || !content) return NextResponse.json({ message: "请填写公告标题和内容。" }, { status: 400 }); const id = `announcement-${Date.now()}-${randomBytes(3).toString("hex")}`; await getDb().execute("INSERT INTO announcements (id, title, content, announcement_type, author_id, is_pinned) VALUES (?, ?, ?, ?, ?, ?)", [id, title, content, type, String(session.id), input.pinned ? 1 : 0]); return NextResponse.json({ id }, { status: 201 }); }
