import { randomBytes } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import type { RowDataPacket } from "mysql2";
import { SESSION_COOKIE, readSession } from "@/lib/auth";
import { getDb } from "@/lib/db";
export const runtime = "nodejs";
async function authorized(request: NextRequest) { const token = request.cookies.get(SESSION_COOKIE)?.value; const session = token ? await readSession(token) : null; return session && ["admin", "superadmin", "manager"].includes(session.role) ? session : null; }
export async function GET(request: NextRequest) { if (!await authorized(request)) return NextResponse.json({ message: "仅管理员可以查看客户资料。" }, { status: 403 }); const [rows] = await getDb().execute<RowDataPacket[]>("SELECT p.id, p.name, p.partner_type AS type, p.contact_person AS contactPerson, p.contact_phone AS contactPhone, p.contact_email AS contactEmail, p.address, p.cooperation, p.status, DATE_FORMAT(p.created_at, '%Y-%m-%d') AS createdAt, COUNT(pr.id) AS projectCount FROM partners p LEFT JOIN projects pr ON pr.partner_id = p.id GROUP BY p.id ORDER BY p.created_at DESC"); return NextResponse.json({ partners: rows.map((row) => ({ ...row, projectCount: Number(row.projectCount) })) }); }
export async function POST(request: NextRequest) { if (!await authorized(request)) return NextResponse.json({ message: "仅管理员可以创建客户。" }, { status: 403 }); const input = await request.json() as Record<string, unknown>; const name = typeof input.name === "string" ? input.name.trim().slice(0, 191) : ""; const contactPerson = typeof input.contactPerson === "string" ? input.contactPerson.trim().slice(0, 100) : ""; const contactPhone = typeof input.contactPhone === "string" ? input.contactPhone.trim().slice(0, 40) : ""; const type = ["association", "college", "enterprise"].includes(String(input.type)) ? String(input.type) : "enterprise"; if (!name || !contactPerson || !contactPhone) return NextResponse.json({ message: "请填写客户名称、联系人和联系电话。" }, { status: 400 }); const id = `partner-${Date.now()}-${randomBytes(3).toString("hex")}`; await getDb().execute("INSERT INTO partners (id, name, partner_type, contact_person, contact_phone, contact_email, address, cooperation) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", [id, name, type, contactPerson, contactPhone, typeof input.contactEmail === "string" ? input.contactEmail.trim() : null, typeof input.address === "string" ? input.address.trim() : null, typeof input.cooperation === "string" ? input.cooperation.trim() : null]); return NextResponse.json({ id }, { status: 201 }); }
