import { randomBytes } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import type { RowDataPacket } from "mysql2";
import { SESSION_COOKIE, readSession } from "@/lib/auth";
import { getDb } from "@/lib/db";

export const runtime = "nodejs";
async function current(request: NextRequest) { const token = request.cookies.get(SESSION_COOKIE)?.value; return token ? readSession(token) : null; }
async function employeeId(accountId: number) { const [rows] = await getDb().execute<RowDataPacket[]>("SELECT id FROM employees WHERE account_user_id = ? LIMIT 1", [accountId]); return rows[0]?.id as string | undefined; }
function map(row: RowDataPacket) { return { ...row, attendees: typeof row.attendees === "string" ? JSON.parse(row.attendees || "[]") : row.attendees || [] }; }
export async function GET(request: NextRequest) { const session = await current(request); if (!session) return NextResponse.json({ message: "请先登录" }, { status: 401 }); const admin = ["admin", "superadmin", "manager"].includes(session.role); const employee = await employeeId(session.id); const [rows] = await getDb().execute<RowDataPacket[]>("SELECT id, title, room, organizer_id AS organizerId, attendees, DATE_FORMAT(start_time, '%Y-%m-%d %H:%i:%s') AS startTime, DATE_FORMAT(end_time, '%Y-%m-%d %H:%i:%s') AS endTime, description, status, minutes FROM meetings ORDER BY start_time DESC"); const meetings = rows.map(map).filter((meeting) => admin || meeting.attendees.includes(employee)); return NextResponse.json({ meetings }); }
export async function POST(request: NextRequest) { const session = await current(request); if (!session || !["admin", "superadmin", "manager"].includes(session.role)) return NextResponse.json({ message: "仅管理员可以创建会议。" }, { status: 403 }); const input = await request.json() as { title?: string; room?: string; startTime?: string; endTime?: string; description?: string; attendees?: string[] }; const title = String(input.title || "").trim().slice(0, 255); const room = String(input.room || "").trim().slice(0, 100); const attendees = Array.isArray(input.attendees) ? [...new Set(input.attendees.filter((id) => typeof id === "string"))] : []; if (!title || !room || !input.startTime || !input.endTime || !attendees.length || new Date(input.endTime) <= new Date(input.startTime)) return NextResponse.json({ message: "请完整填写会议资料并选择参会员工。" }, { status: 400 }); const id = `meeting-${Date.now()}-${randomBytes(3).toString("hex")}`; await getDb().execute("INSERT INTO meetings (id, title, room, organizer_id, attendees, start_time, end_time, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", [id, title, room, String(session.id), JSON.stringify(attendees), input.startTime, input.endTime, String(input.description || "").trim()]); return NextResponse.json({ id }, { status: 201 }); }
